export const CATEGORY_ACTION_TYPES = {
  SET_CATEGORIES: 'category/SET_CATEGORIES',
  FETCH_CATEGORIES_START: 'category/FETCH_ACTEGORIES_START',
  FETCH_CATEGORIES_SUCCESS: 'category/FETCH_ACTEGORIES_SUCCESS',
  FETCH_CATEGORIES_FAILED: 'category/FETCH_ACTEGORIES_FAILED',
};